baseURL = "https://example.com/"
languageCode = "en-us"
title = "0xstark"
theme = "PaperMod"


[params]
  defaultTheme = "light"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowToc = false
  mainSections = ["posts"]
  baseURL = "https://jjmstark.github.io/website/"


[params.cover]
  hideInList = true


[params.homeInfoParams]
  title = "About"
  content = "I'm Josh Stark, and I work for [Ethereum](https://ethereum.org/) at the [Ethereum Foundation](https://ethereum.foundation/) where I serve on the management team. Previously I co-founded [ETHGlobal](https://ethglobal.com/) and [L4](https://x.com/L4ventures/status/1006543147290292224?s=20)."
